package com.example.payments.model;

import com.example.selector.GenerateSelector;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

/**
 * Root of the example model graph, shaped like a typical generated API model object:
 * private fields with plain getters and setters.
 *
 * <p>This is the only type in the package carrying {@link GenerateSelector} — selectors for
 * {@link Party}, {@link Agent}, {@link FinancialInstitution}, {@link Account} and {@link Amount}
 * are generated by recursion.
 */
@GenerateSelector
public class Payment {

    private String id;
    private Amount amount;
    private Party payee;
    private Party payer;
    private Account creditorAccount;
    private int retryCount;
    private boolean urgent;
    private LocalDate valueDate;
    private Status status;
    private List<String> tags;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Amount getAmount() {
        return amount;
    }

    public void setAmount(Amount amount) {
        this.amount = amount;
    }

    public Party getPayee() {
        return payee;
    }

    public void setPayee(Party payee) {
        this.payee = payee;
    }

    public Party getPayer() {
        return payer;
    }

    public void setPayer(Party payer) {
        this.payer = payer;
    }

    public Account getCreditorAccount() {
        return creditorAccount;
    }

    public void setCreditorAccount(Account creditorAccount) {
        this.creditorAccount = creditorAccount;
    }

    /** Primitive on the model; the selector exposes it boxed so it can report "unknown". */
    public int getRetryCount() {
        return retryCount;
    }

    public void setRetryCount(int retryCount) {
        this.retryCount = retryCount;
    }

    public boolean isUrgent() {
        return urgent;
    }

    public void setUrgent(boolean urgent) {
        this.urgent = urgent;
    }

    public LocalDate getValueDate() {
        return valueDate;
    }

    public void setValueDate(LocalDate valueDate) {
        this.valueDate = valueDate;
    }

    /** An enum: a leaf, returned as-is rather than descended into. */
    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    /** A collection: also a leaf — the selector navigates graphs, it does not iterate them. */
    public List<String> getTags() {
        return tags;
    }

    public void setTags(List<String> tags) {
        this.tags = tags;
    }

    /** Not a property: has a parameter, so no selector method is generated for it. */
    public BigDecimal getAmountIn(String currency) {
        return amount == null ? null : amount.getValue();
    }
}
